training:
  bs: 512
  epochs: 1
  log_freq: 200
  lr: 0.0005
  patience: 5
  seed: 12412421
network:
  deepfm:
    hidden_dim: 128
    k: 256
    num_hidden_layers: 3
  transformer:
    k: 256
    num_heads: 8
    num_transformer_blocks: 4
    widening_factor: 4
  transfm:
    k: 256
    num_transformer_blocks: 4
    num_heads: 4
    widening_factor: 4
